---
# tasks file for server
- name: Update apt chache
  apt: update_cache=yes
  sudo: yes

- name: install required packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - php5-mysql
    - php5
    - libapache2-mod-php5
    - php5-mcrypt
    - python-mysqldb
